version: '3.8'
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: chinmayapradhan/backend:1.0
    env_file:
      - ./.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: chinmayapradhan/frotend:1.0
    env_file:
      - ./.env.sample
    ports:
      - "5173:5173"

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
      - 6379
    depends_on:
      - mongodb

  mongoimport:
    container_name: mongoimport
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    depends_on:
      - mongodb
    command: ["mongoimport", "--host", "mongodb", "--db", "wanderlust", "--collection", "posts", "--file", "/data/sample_posts.json", "--jsonArray"]
    entrypoint: []

